export const PROMOTION_LIST_REQUEST = "PROMOTION_LIST_REQUEST";
export const PROMOTION_LIST_SUCCESS = "PROMOTION_LIST_SUCCESS";
export const PROMOTION_LIST_FAIL = "PROMOTION_LIST_FAIL";

export const PROMOTION_CREATE_REQUEST = "PROMOTION_CREATE_REQUEST";
export const PROMOTION_CREATE_SUCCESS = "PROMOTION_CREATE_SUCCESS";
export const PROMOTION_CREATE_FAIL = "PROMOTION_CREATE_FAIL";
export const PROMOTION_CREATE_RESET = "PROMOTION_CREATE_RESET";
